teams = {
  bots = [
    "BrewTestBot",
    "BrewSponsorsBot",
  ],
  maintainers = {
    brew = [
      "Bo98",
      "EricFromCanada",
      "MikeMcQuaid",
      "Rylan12",
      "SMillerDev",
      "ZhongRuoyu",
      "apainintheneck",
      "bayandin",
      "carlocab",
      "cho-m",
      "dduugg",
      "iMichka",
      "issyl0",
      "miccal",
      "nandahkrishna",
      "p-linnane",
      "reitermarkus",
      "samford",
      "woodruffw",
    ],
    cask = [
      "Bo98",
      "Rylan12",
      "SMillerDev",
      "alebcay",
      "bevanjkay",
      "chenrui333",
      "cho-m",
      "khipp",
      "krehel",
      "miccal",
      "p-linnane",
      "razvanazamfirei",
      "reitermarkus",
      "samford",
    ],
    ci-orchestrator = [
      "Bo98",
      "carlocab",
    ],
    core = [
      "Bo98",
      "EricFromCanada",
      "MikeMcQuaid",
      "Moisan",
      "Rylan12",
      "SMillerDev",
      "ZhongRuoyu",
      "alebcay",
      "bayandin",
      "bevanjkay",
      "branchvincent",
      "carlocab",
      "chenrui333",
      "cho-m",
      "dtrodrigues",
      "fxcoudert",
      "iMichka",
      "issyl0",
      "krehel",
      "miccal",
      "nandahkrishna",
      "p-linnane",
      "samford",
      "stefanb",
      "timsutton",
      "woodruffw",
    ],
    formulae-web = [
      "EricFromCanada",
      "MikeMcQuaid",
      "Rylan12",
      "SMillerDev",
    ],
    ops = [
      "Bo98",
      "Rylan12",
      "carlocab",
      "fxcoudert",
      "nandahkrishna",
      "p-linnane",
    ],
    tsc = [
      "Bo98",
      "MikeMcQuaid",
      "Rylan12",
      "fxcoudert",
      "iMichka",
    ],
  },
  members = [
    "Bo98",
    "DomT4",
    "EricFromCanada",
    "MikeMcQuaid",
    "Moisan",
    "Rylan12",
    "SMillerDev",
    "ZhongRuoyu",
    "alebcay",
    "alex",
    "apainintheneck",
    "bayandin",
    "bevanjkay",
    "branchvincent",
    "carlocab",
    "chenrui333",
    "cho-m",
    "colindean",
    "danielnachun",
    "dawidd6",
    "dduugg",
    "dtrodrigues",
    "fxcoudert",
    "gromgit",
    "iMichka",
    "issyl0",
    "jacobbednarz",
    "johndbritton",
    "khipp",
    "krehel",
    "lembacon",
    "maxim-belkin",
    "miccal",
    "mistydemeo",
    "mozzadrella",
    "nandahkrishna",
    "p-linnane",
    "razvanazamfirei",
    "reitermarkus",
    "samford",
    "scpeters",
    "singingwolfboy",
    "sjackman",
    "stefanb",
    "tani",
    "timsutton",
    "victorpopkov",
    "vitorgalvao",
    "whoiswillma",
    "woodruffw",
    "xu-cheng",
  ],
  plc = [
    "MikeMcQuaid",
    "colindean",
    "issyl0",
    "mozzadrella",
    "p-linnane",
  ],
  security = [
    "MikeMcQuaid",
    "p-linnane",
    "woodruffw",
  ],
  taps = {
    bundle = [
      "EricFromCanada",
      "jacobbednarz",
      "MikeMcQuaid",
    ],
    linux-fonts = [
      "sjackman",
      "tani",
    ],
    pip = [
    "alex",
    "woodruffw",
    ],
    services = [
      "SMillerDev",
    ],
  },
}

github_admins = [ "issyl0", "p-linnane", "bo98", "mikemcquaid" ]
